### ISSUE TITLE
Refusing to install XXX as a dependency of itself

### ISSUE THREAD

**Issue by ddossot** [mulesoft/raml-client-generator#11]
After generating a JavaScript client, I follow the generated README file:

    $ npm install my-api --save
    npm WARN install Refusing to install my-api as a dependency of itself

Not sure what to do next.

**Comment by blakeembrey** [comment]
@ddossot Where are you trying to install it? You can't install it inside of itself, you need to publish it somewhere and install from there (GitHub, npm, `npm link`).

**Comment by ddossot** [comment]
This isn't clear in the README. I thought the command would install it inside my local Node repo so I could use it in other Node projects.

**Comment by blakeembrey** [comment]
@ddossot Where should that even be written? I've never seen anyone write in a README that you shouldn't install it in itself but inside of the target application. I'm not really sure what the trouble is, to be honest. You tried to install within itself, I'm not sure what you'd expect to happen. We could provide instructions for installing from git or locally, but if it got published it will likely need manual intervention on the readme since it's not standard.

**Comment by ddossot** [comment]
I guess I got confused by the wording in the README file. I thought it was the first thing to do after generating the client. I didn't realize something else was needed to be done before being able to run `npm install my-api --save`, nor I didn't realize that it would try to install in itself. I'm not very smart but it's clearly not something I would attempt if I knew it would do it.

I guess what I'm trying to ask is: could it be clearly said what it is that needs to be done before being able to run `npm install my-api --save`?

**Comment by blakeembrey** [comment]
@ddossot Ok, cool. Now I understand where you're getting stuck. We could print out instructions via the CLI for the next steps before being able to install it within your own projects. The generated client is the code that is expected to end up on a package repository (like github or npm).

**Comment by usarid** [comment]
OK, rising above the fray for a sec: perhaps, @ddossot, you were expecting
instructions to allow you to install the client globally, so it can be
included in any node project's dependencies?

Otherwise, Blake, is there something in the generated readme file that
could be made clearer?

Can you attach that file, @ddossot?

**Comment by usarid** [comment]
Also, perhaps some usage examples for a generated client would be useful.

**Comment by blakeembrey** [comment]
@usarid There are usage example in the readme and installation instructions, but they are targetted towards people who are installing it - not publishing it. The issue is that @ddossot was trying to do the publish step as the install step, that's why you either need to put the module onto github or npm, or if you want to keep it locally you can use `npm link`.

**Comment by usarid** [comment]
It would be clearer if I saw them, I suppose. Maybe we should have
instructions there for both cases, so people would understand what their
options are, and do the right one?

**Comment by ddossot** [comment]
I'm used to build/dependency managers like `Maven`, `Leiningen`, `Gradle` and `sbt`, where you can install globally (either locally or on a remote server) a package so that other applications can use it (as you said @usarid ).

So I wrongfully, based on my biased experience, assumed that the next step would be to run an equivalent `npm` command so the generated client would be installed globally on my machine, so that other projects could start using it.

It seems in `npm` what I wrongly thought to be called `install` is actually called `publish`. Hence me wrongly interpreting the first step of the README as the first thing to do to be able to use the generated code.

I imagine all this is pretty darn obvious for `npm` users, but like me, many users will come from the JVM world and fall into the trap.

Why would JVM users consider the JS client? Well, I saw the "download client link" in the corner of the RAML console and started exploring this generated JS client. This client interests me to build test suites that can be run from the command line: JS/Node seems a good platform for this.

So I guess some sort of "first steps for npm n00bs" would be a good addition in the README, even a one-liner so newcomers would have a hint to the next steps after generating the code.

**Comment by blakeembrey** [comment]
@ddossot Ah, yes. Usage inside of downloads is difficult. We could give more context in the readme but I think it should be written from the viewpoint of it existing on github or something similar and not locally. It'll be the same usage, but there will be a first step for downloading from git. Normally you won't want to link *only* locally anyway since then no one else can use it (push to github or npm).

**Comment by ddossot** [comment]
I see, one could place the generated client in a particular project and npm link it to bypass any need to publish it. It makes sense.

So maybe the README could just have a simple addition:

    After publishing this client to github or npm, run `npm install...`

I think this would be enough to act as a signal for `npm` newbies that something else is needed. A Google search will do the rest.

**Comment by blakeembrey** [comment]
That's possible, but the README right now is what's published. It's kind of weird to be on npm and trying to use a module and read instructions on it to be published to npm. That's the issue you're having, is that the README is meant for consumers and not publishers. Now, we could add a separate `INSTALL.md` file with this information instead that can be ignored from git and npm.

**Comment by usarid** [comment]
Note that one important usecase will be for internal APIs where there may be pushing to or pulling from a source control system, but external usage of github or npm won't be relevant.
In general, given the importance and broad applicability of client generators, let's try to over-communicate and broaden the reach as much as possible.






On Tue, Feb 17, 2015 at 8:00 PM -0800, "Blake Embrey" <notifications@github.com> wrote:












That's possible, but the README right now is what's published. It's kind of weird to be on npm and trying to use a module and read instructions on it to be published to npm. That's the issue you're having, is that the README is meant for consumers and not publishers. Now, we could add a separate INSTALL.md file with this information instead that can be ignored from git and npm.

**Comment by ddossot** [comment]
@blakeembrey Fair point. So clearly, _this wasn't the README I was looking for_. The actual readme where a potential instruction for publishing or linking is this one: https://github.com/mulesoft/raml-client-generator/blob/master/README.md I actually followed the instructions there, generated the client then ... followed the instructions in the generated readme :facepalm:

A little more verbiage in https://github.com/mulesoft/raml-client-generator/blob/master/README.md#usage would do the trick then.

:+1: @usarid about internal APIs and over-communicating :bow:

**Comment by blakeembrey** [comment]
@ddossot Feel free to keep it open to keep iterating. I'm hesitant to add it to the global readme since this module is intended to serve multiple languages and node instructions are really suitable. I've added some initial installation instructions with https://github.com/mulesoft/raml-client-generator/commit/5bf404801f389274e03fc61fa417f1f8e1771833, but we can reopen to keep iterating. For the generated README, I want to get a manifest file into client generation so that we can define module names and whether it'll ever actually exist on npm, github, etc. That's tracked with #12.

**Comment by ddossot** [comment]
I'm super happy with `INSTALL.md` in 5bf4048, thanks a lot for this. I think this issue can be kept closed as you've addressed the "lost n00b" issue via this new guide. I'll be tracking #12 in order to try on my side and potentially give you n00b-grade feedback on it.

**Comment by qiaocuixinzhiweini** [comment]
I have the same problem,and i found the reason and fixed if finally.In package.json,name should not the same to the module you want to install.

**Comment by OmarZeidan** [comment]
Just happened to me trying to install react for a require call, however, fixed this by changing the name specified within my package.json file.

**Comment by smancang** [comment]
All these issues occur because your name node in your package.json is the same with the package name that you are going to install.Check it,you'll fix it.

**Comment by LabbiqX** [comment]
Yes, It is definitely so. I have the same problem, and this solution works.

**Comment by eminoda** [comment]
@smancang  Thanks,friends. i use typescript,then meet this problem

**Comment by thepowderriverfarrier** [comment]
The above answer by smancang is the working solution.  Ran into that on Windoze Server 2012;  ended up having to delete all the files then rebuild them then the npm install mssql worked fine.

**Comment by eyeoftigers** [comment]
http://thisdavej.com/node-newbie-error-npm-refusing-to-install-package-as-a-dependency-of-itself/

On line 2, we see that the name of our project is winston.  I don’t think npm likes that since we are trying to install a package named “winston”.  Let’s rename our project to “winston-test”, and save the package.json file:

**Comment by isaan** [comment]
> https://github.com/mulesoft-labs/raml-client-generator/issues/11#issuecomment-230403370
@smancang works for me, thanks a lot
